name = "i18n"
description = "Message-formatting library for a strict, deterministic subset of ICU"
version = "1.1.0"
authors = ["Bent Bracke"]
maintainers = ["Bent Bracke <bent@bracke.dk>"]
maintainers-logins = ["bracke"]
licenses = "MIT"
website = "https://github.com/bracke/i18n"
tags = ["messages","i18n","locales"]
project-files = ["i18n.gpr"]

[[depends-on]]
gnat = ">=12"

[[actions]]
type = "test"
command = ["sh", "-c", "cd check_i18n && alr build && ./bin/check_i18n --skip-alr-test"]
